/**
 * Single source of truth for every status the dashboard renders.
 *
 * The audit found order-status labels/colors duplicated across three files
 * (Badge.tsx, tokens.ts, @tamem/types) and drifting. This registry replaces
 * them: each status → { label, tone, icon }. Tones map to static Tailwind
 * class sets (dynamic `bg-${x}` classes don't get generated by Tailwind).
 * Every status carries an icon so it doesn't rely on color alone (colorblind).
 */
import {
  Ban,
  CheckCircle2,
  Clock,
  CreditCard,
  Inbox,
  PackageCheck,
  RotateCcw,
  Search,
  Tag,
  Truck,
  UserCheck,
  UserX,
  XCircle,
  type LucideIcon,
} from 'lucide-react';

export type Tone =
  | 'blue'
  | 'purple'
  | 'sky'
  | 'amber'
  | 'cyan'
  | 'teal'
  | 'green'
  | 'emerald'
  | 'zinc'
  | 'red';

/** Static class sets per tone — soft badge, solid dot, and accent ring. */
export const TONE: Record<Tone, { badge: string; dot: string; soft: string; text: string }> = {
  blue: {
    badge: 'bg-blue-100 text-blue-700',
    dot: 'bg-blue-500',
    soft: 'bg-blue-50',
    text: 'text-blue-600',
  },
  purple: {
    badge: 'bg-purple-100 text-purple-700',
    dot: 'bg-purple-500',
    soft: 'bg-purple-50',
    text: 'text-purple-600',
  },
  sky: {
    badge: 'bg-sky-100 text-sky-700',
    dot: 'bg-sky-500',
    soft: 'bg-sky-50',
    text: 'text-sky-600',
  },
  amber: {
    badge: 'bg-amber-100 text-amber-700',
    dot: 'bg-amber-500',
    soft: 'bg-amber-50',
    text: 'text-amber-600',
  },
  cyan: {
    badge: 'bg-cyan-100 text-cyan-700',
    dot: 'bg-cyan-500',
    soft: 'bg-cyan-50',
    text: 'text-cyan-600',
  },
  teal: {
    badge: 'bg-teal-100 text-teal-700',
    dot: 'bg-teal-500',
    soft: 'bg-teal-50',
    text: 'text-teal-600',
  },
  green: {
    badge: 'bg-green-100 text-green-700',
    dot: 'bg-green-500',
    soft: 'bg-green-50',
    text: 'text-green-600',
  },
  emerald: {
    badge: 'bg-emerald-100 text-emerald-700',
    dot: 'bg-emerald-500',
    soft: 'bg-emerald-50',
    text: 'text-emerald-600',
  },
  zinc: {
    badge: 'bg-zinc-200 text-zinc-700',
    dot: 'bg-zinc-400',
    soft: 'bg-zinc-50',
    text: 'text-zinc-600',
  },
  red: {
    badge: 'bg-red-100 text-red-700',
    dot: 'bg-red-500',
    soft: 'bg-red-50',
    text: 'text-red-600',
  },
};

export interface StatusMeta {
  label: string;
  tone: Tone;
  icon: LucideIcon;
}

/** Order lifecycle — labels match @tamem/types ORDER_STATUS_AR. */
export const ORDER_STATUS: Record<string, StatusMeta> = {
  NEW: { label: 'جديد', tone: 'blue', icon: Inbox },
  UNDER_REVIEW: { label: 'قيد المراجعة', tone: 'purple', icon: Search },
  PRICED: { label: 'تم التسعير', tone: 'sky', icon: Tag },
  AWAITING_CUSTOMER_APPROVAL: { label: 'بانتظار العميل', tone: 'amber', icon: Clock },
  ACCEPTED: { label: 'مقبول', tone: 'emerald', icon: CheckCircle2 },
  DRIVER_ASSIGNED: { label: 'تعيين سائق', tone: 'cyan', icon: Truck },
  PICKED_UP: { label: 'تم الاستلام', tone: 'teal', icon: PackageCheck },
  IN_ROUTE: { label: 'في الطريق', tone: 'amber', icon: Truck },
  DELIVERED: { label: 'تم التسليم', tone: 'green', icon: CheckCircle2 },
  COMPLETED: { label: 'مكتمل', tone: 'green', icon: CheckCircle2 },
  CANCELLED: { label: 'ملغي', tone: 'zinc', icon: XCircle },
  REJECTED: { label: 'مرفوض', tone: 'red', icon: Ban },
};

/** Payment status. */
export const PAYMENT_STATUS: Record<string, StatusMeta> = {
  PENDING: { label: 'معلّق', tone: 'amber', icon: Clock },
  PAID: { label: 'مدفوع', tone: 'green', icon: CheckCircle2 },
  FAILED: { label: 'فشل', tone: 'red', icon: XCircle },
  REFUNDED: { label: 'مسترد', tone: 'zinc', icon: RotateCcw },
  CONFIRMED: { label: 'مؤكّد', tone: 'green', icon: CheckCircle2 },
  REJECTED: { label: 'مرفوض', tone: 'red', icon: Ban },
};

/** Driver availability. */
export const DRIVER_STATUS: Record<string, StatusMeta> = {
  AVAILABLE: { label: 'متاح', tone: 'green', icon: UserCheck },
  BUSY: { label: 'مشغول', tone: 'amber', icon: Clock },
  OFFLINE: { label: 'غير متصل', tone: 'zinc', icon: UserX },
};

export const PAYMENT_ICON = CreditCard;

export function orderStatusMeta(status: string): StatusMeta {
  return ORDER_STATUS[status] ?? { label: status, tone: 'zinc', icon: Inbox };
}
